### PR TITLE
avoid confusion with vtil::lifter::amd64 and fix pop rsp/pop[rsp+x]

### PR DESCRIPTION
**Pull request by Mahorori**

### CODE REVIEW

**Comment by can1357** [comment]
image
Added a few test cases but `push rsp` doesn't seem to pass so I'll fix that and push along with the POP fixes, thanks for the PR!

**Comment by Mahorori** [comment]
```
			X86_INS_PUSH,
			[ ] ( basic_block* block, const instruction_info& insn )
			{
				if (insn.operands[0].type == X86_OP_REG && insn.operands[0].reg == X86_REG_RSP)
				{
					auto tmp = block->tmp(64);
					block->mov(tmp, X86_REG_RSP);
					block->sub(X86_REG_RSP, 8);
					block->str(X86_REG_RSP, 0, tmp);
				}
				else
				{
					auto oper = load_operand(block, insn, 0);
					if (oper.bit_count() == 16)
						block->sub(X86_REG_RSP, 2);
					else
						block->sub(X86_REG_RSP, 8);
					block->str(X86_REG_RSP, 0, oper);
				}
			}
```
I wrote like above but dont wanna mess your coding style so

**Comment by can1357** [comment]
IMO the primary cause of this issue is that load_operand doesn't really load it but instead references it. I'll make it move to a temporary first like below:
```cpp
	operand load_operand( basic_block* block, const instruction_info& insn, size_t idx )
	{
		// Grab the operand at the current index.
		const auto& opr = insn.operands[ idx ];

		// Check the type and return relevant value accordingly.
		switch ( opr.type )
		{
			case X86_OP_IMM:
				return { opr.imm, opr.size * 8 };
			case X86_OP_REG:
			{
				auto tmp = block->tmp( opr.size * 8 ); // <--------- 
				auto reg = reg2op( opr.reg );
				block->mov( tmp, reg );
				return { tmp };
			}
			case X86_OP_MEM:
			{
				auto tmp = block->tmp( opr.size * 8 );
				block
					->ldd( tmp, get_disp_from_operand( block, opr ), 0 );
				return { tmp };
			}
			default:
				unreachable();
		}
	}
```
Should prevent future problems with this function as well.

**Comment by can1357** [comment]
As for the POP:
```cpp
			X86_INS_POP,
			[ ] ( basic_block* block, const instruction_info& insn )
			{
				auto tmp = block->tmp( 64 );
				block->ldd( tmp, X86_REG_RSP, block->sp_offset );
				if ( insn.operands[ 0 ].size == 2 )
					block->add( X86_REG_RSP, 2 );
				else
					block->add( X86_REG_RSP, 8 );
				store_operand( block, insn, 0, tmp );
			}
```
This seems to work without any special checks for RSP, just by re-ordering.

image

Let me know if you have any issues after the fix.

**Pull request merged**
